package com.final_year.v2.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "payments")
@Data
@NoArgsConstructor
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String transactionId;   // UUID generated by us

    private String pidx;            // Khalti's payment ID

    @Column(nullable = false)
    private String gateway;         // "esewa" or "khalti"

    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    @Column(nullable = false)
    private String status;          // PENDING, SUCCESS, FAILED

    @Column(nullable = false)
    private Long userId;            // ID of the user who initiated payment

    private String planId;          // "view" or "creator" (from frontend)

    private String billingCycle;    // "monthly", "half", "yearly"

    private LocalDateTime createdAt = LocalDateTime.now();
    private LocalDateTime updatedAt;
}
